assert False, "(Intentionally thrown exception)"
